
import { Club } from './types';

export const TARGET_SCORE = 501;

export const ENGLISH_CLUBS: Club[] = [
  // Premier League
  { id: 'pl-1', name: 'Arsenal', league: 'Premier League' },
  { id: 'pl-2', name: 'Aston Villa', league: 'Premier League' },
  { id: 'pl-3', name: 'Bournemouth', league: 'Premier League' },
  { id: 'pl-4', name: 'Brentford', league: 'Premier League' },
  { id: 'pl-5', name: 'Brighton & Hove Albion', league: 'Premier League' },
  { id: 'pl-6', name: 'Chelsea', league: 'Premier League' },
  { id: 'pl-7', name: 'Crystal Palace', league: 'Premier League' },
  { id: 'pl-8', name: 'Everton', league: 'Premier League' },
  { id: 'pl-9', name: 'Fulham', league: 'Premier League' },
  { id: 'pl-10', name: 'Ipswich Town', league: 'Premier League' },
  { id: 'pl-11', name: 'Leicester City', league: 'Premier League' },
  { id: 'pl-12', name: 'Liverpool', league: 'Premier League' },
  { id: 'pl-13', name: 'Manchester City', league: 'Premier League' },
  { id: 'pl-14', name: 'Manchester United', league: 'Premier League' },
  { id: 'pl-15', name: 'Newcastle United', league: 'Premier League' },
  { id: 'pl-16', name: 'Nottingham Forest', league: 'Premier League' },
  { id: 'pl-17', name: 'Southampton', league: 'Premier League' },
  { id: 'pl-18', name: 'Tottenham Hotspur', league: 'Premier League' },
  { id: 'pl-19', name: 'West Ham United', league: 'Premier League' },
  { id: 'pl-20', name: 'Wolverhampton Wanderers', league: 'Premier League' },

  // Championship
  { id: 'ch-1', name: 'Blackburn Rovers', league: 'Championship' },
  { id: 'ch-2', name: 'Bristol City', league: 'Championship' },
  { id: 'ch-3', name: 'Burnley', league: 'Championship' },
  { id: 'ch-4', name: 'Cardiff City', league: 'Championship' },
  { id: 'ch-5', name: 'Coventry City', league: 'Championship' },
  { id: 'ch-6', name: 'Derby County', league: 'Championship' },
  { id: 'ch-7', name: 'Hull City', league: 'Championship' },
  { id: 'ch-8', name: 'Leeds United', league: 'Championship' },
  { id: 'ch-9', name: 'Luton Town', league: 'Championship' },
  { id: 'ch-10', name: 'Middlesbrough', league: 'Championship' },
  { id: 'ch-11', name: 'Millwall', league: 'Championship' },
  { id: 'ch-12', name: 'Norwich City', league: 'Championship' },
  { id: 'ch-13', name: 'Oxford United', league: 'Championship' },
  { id: 'ch-14', name: 'Plymouth Argyle', league: 'Championship' },
  { id: 'ch-15', name: 'Portsmouth', league: 'Championship' },
  { id: 'ch-16', name: 'Preston North End', league: 'Championship' },
  { id: 'ch-17', name: 'Queens Park Rangers', league: 'Championship' },
  { id: 'ch-18', name: 'Sheffield United', league: 'Championship' },
  { id: 'ch-19', name: 'Sheffield Wednesday', league: 'Championship' },
  { id: 'ch-20', name: 'Stoke City', league: 'Championship' },
  { id: 'ch-21', name: 'Sunderland', league: 'Championship' },
  { id: 'ch-22', name: 'Swansea City', league: 'Championship' },
  { id: 'ch-23', name: 'Watford', league: 'Championship' },
  { id: 'ch-24', name: 'West Bromwich Albion', league: 'Championship' },

  // League One
  { id: 'l1-1', name: 'Barnsley', league: 'League One' },
  { id: 'l1-2', name: 'Birmingham City', league: 'League One' },
  { id: 'l1-3', name: 'Blackpool', league: 'League One' },
  { id: 'l1-4', name: 'Bolton Wanderers', league: 'League One' },
  { id: 'l1-5', name: 'Bristol Rovers', league: 'League One' },
  { id: 'l1-6', name: 'Burton Albion', league: 'League One' },
  { id: 'l1-7', name: 'Cambridge United', league: 'League One' },
  { id: 'l1-8', name: 'Charlton Athletic', league: 'League One' },
  { id: 'l1-9', name: 'Crawley Town', league: 'League One' },
  { id: 'l1-10', name: 'Exeter City', league: 'League One' },
  { id: 'l1-11', name: 'Huddersfield Town', league: 'League One' },
  { id: 'l1-12', name: 'Leyton Orient', league: 'League One' },
  { id: 'l1-13', name: 'Lincoln City', league: 'League One' },
  { id: 'l1-14', name: 'Mansfield Town', league: 'League One' },
  { id: 'l1-15', name: 'Northampton Town', league: 'League One' },
  { id: 'l1-16', name: 'Peterborough United', league: 'League One' },
  { id: 'l1-17', name: 'Reading', league: 'League One' },
  { id: 'l1-18', name: 'Rotherham United', league: 'League One' },
  { id: 'l1-19', name: 'Shrewsbury Town', league: 'League One' },
  { id: 'l1-20', name: 'Stevenage', league: 'League One' },
  { id: 'l1-21', name: 'Stockport County', league: 'League One' },
  { id: 'l1-22', name: 'Wigan Athletic', league: 'League One' },
  { id: 'l1-23', name: 'Wrexham', league: 'League One' },
  { id: 'l1-24', name: 'Wycombe Wanderers', league: 'League One' },

  // League Two
  { id: 'l2-1', name: 'Accrington Stanley', league: 'League Two' },
  { id: 'l2-2', name: 'AFC Wimbledon', league: 'League Two' },
  { id: 'l2-3', name: 'Barrow', league: 'League Two' },
  { id: 'l2-4', name: 'Bromley', league: 'League Two' },
  { id: 'l2-5', name: 'Carlisle United', league: 'League Two' },
  { id: 'l2-6', name: 'Cheltenham Town', league: 'League Two' },
  { id: 'l2-7', name: 'Chesterfield', league: 'League Two' },
  { id: 'l2-8', name: 'Colchester United', league: 'League Two' },
  { id: 'l2-9', name: 'Crewe Alexandra', league: 'League Two' },
  { id: 'l2-10', name: 'Doncaster Rovers', league: 'League Two' },
  { id: 'l2-11', name: 'Fleetwood Town', league: 'League Two' },
  { id: 'l2-12', name: 'Gillingham', league: 'League Two' },
  { id: 'l2-13', name: 'Grimsby Town', league: 'League Two' },
  { id: 'l2-14', name: 'Harrogate Town', league: 'League Two' },
  { id: 'l2-15', name: 'Milton Keynes Dons', league: 'League Two' },
  { id: 'l2-16', name: 'Morecambe', league: 'League Two' },
  { id: 'l2-17', name: 'Newport County', league: 'League Two' },
  { id: 'l2-18', name: 'Notts County', league: 'League Two' },
  { id: 'l2-19', name: 'Port Vale', league: 'League Two' },
  { id: 'l2-20', name: 'Salford City', league: 'League Two' },
  { id: 'l2-21', name: 'Swindon Town', league: 'League Two' },
  { id: 'l2-22', name: 'Tranmere Rovers', league: 'League Two' },
  { id: 'l2-23', name: 'Walsall', league: 'League Two' },
  { id: 'l2-24', name: 'Harrogate Town', league: 'League Two' },
].sort((a, b) => a.name.localeCompare(b.name));
